//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Student_Application.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class StudentDetail
    {
        public int StudentDetials_ID { get; set; }
        public int Student_ID { get; set; }
        public Nullable<decimal> Marks { get; set; }
        public int Subject_ID { get; set; }
		public string First_Name { get; set; }
		public string Last_Name { get; set; }
		public string Class { get; set; }

		public string Subject_Name { get; set; }

		public virtual Student Student { get; set; }
        public virtual Subject Subject { get; set; }

		//public List<Student> StudentList { get; set; }
		//public List<Subject> SubjectList { get; set; }
	}
}
